{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import Flask\n",
    "from flask_restful import Resource, Api\n",
    "from ipynb.fs.full.Secure_Check_Authorization_121 import authenticate, identity\n",
    "from flask_jwt import JWT, jwt_required\n",
    "from flask_sqlalchemy import SQLAlchemy\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'C:\\\\Users\\\\ritis\\\\Documents\\\\Jupyter Notebook Files\\\\Flask\\\\REST_119_122'"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "os.getcwd()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask_sqlalchemy\\__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.\n",
      "  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '\n"
     ]
    }
   ],
   "source": [
    "app = Flask(import_name = __name__)\n",
    "app.config['SECRET_KEY'] = 'mysecretkey'\n",
    "\n",
    "base_dir = os.path.abspath(path = os.path.dirname(p = '__file__'))\n",
    "\n",
    "app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(base_dir, 'data.sqlite')\n",
    "app.config['SQL_ALCHEMY_TRACK_MODIFICATIONS'] = False\n",
    "\n",
    "db = SQLAlchemy(app = app)\n",
    "api = Api(app = app)\n",
    "jwt = JWT(app= app, authentication_handler=authenticate, identity_handler=identity)\n",
    "\n",
    "\n",
    "\n",
    "# The format to be stored in the list will be like : [{'name' :'Ritish'},{'name' : 'Rohit'}]\n",
    "#puppies = []\n",
    "\n",
    "class Puppy(db.Model):\n",
    "    name = db.Column(db.String(length = 80), primary_key = True)\n",
    "    \n",
    "    def __init__(self, name):\n",
    "        self.name = name\n",
    "        \n",
    "    def json(self):\n",
    "        return {'name' : self.name}\n",
    "    \n",
    "\n",
    "class PuppyNames(Resource):\n",
    "    \n",
    "    def get(self, name):  \n",
    "#         for pup in puppies:\n",
    "#             if pup['name'] == name:\n",
    "#                 return pup\n",
    "#         return {'name' : None}, 404\n",
    "\n",
    "        pup = Puppy.query.filter_by(name = name).first()\n",
    "        if pup:\n",
    "            return pup.json()\n",
    "        else:\n",
    "            return {'name' : None}, 404\n",
    "            \n",
    "    \n",
    "    \n",
    "    def post(self, name):\n",
    "#         pup = {'name' : name}\n",
    "#         puppies.append(pup)\n",
    "#         return pup\n",
    "    \n",
    "        pup = Puppy(name = name)\n",
    "        db.session.add(pup)\n",
    "        db.session.commit()\n",
    "        return pup.json()\n",
    "        \n",
    "        \n",
    "    \n",
    "    def delete(self, name):  \n",
    "#         for ind, pup in enumerate(puppies):\n",
    "#             if pup['name'] == name:\n",
    "#                 deleted_pup = puppies.pop(ind)\n",
    "#                 return {'note': 'Delete Successful'}\n",
    "            \n",
    "#             return {'name' : None}, 404\n",
    "\n",
    "        pup = Puppy.query.filter_by(name = name).first()\n",
    "        if pup : \n",
    "            db.session.delete(pup)\n",
    "            db.session.commit()\n",
    "    \n",
    "            return {'note' : 'Delete Successful'}\n",
    "        else :\n",
    "            return {'name' : None}, 404\n",
    "\n",
    "\n",
    "# class to generate all the presently available puppies\n",
    "\n",
    "class Allnames(Resource):\n",
    "    \n",
    "    #@jwt_required()\n",
    "    def get(self):\n",
    "#         return {'puppies' : puppies}\n",
    "        puppies = Puppy.query.all()\n",
    "        return [pup.json() for pup in puppies]\n",
    "\n",
    "\n",
    "api.add_resource(PuppyNames, '/puppy/<string:name>')\n",
    "api.add_resource(Allnames, '/puppies')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "db.create_all()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: Do not use the development server in a production environment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: on\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [22/Nov/2019 09:30:30] \"POST /puppy/Avik HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [22/Nov/2019 09:30:37] \"POST /puppy/Rohit HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [22/Nov/2019 09:30:43] \"POST /puppy/Avik HTTP/1.1\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 2309, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 2295, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask_restful\\__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1741, in handle_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\_compat.py\", line 34, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask_restful\\__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\_compat.py\", line 34, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask_restful\\__init__.py\", line 458, in wrapper\n",
      "    resp = resource(*args, **kwargs)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\views.py\", line 88, in view\n",
      "    return self.dispatch_request(*args, **kwargs)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask_restful\\__init__.py\", line 573, in dispatch_request\n",
      "    resp = meth(*args, **kwargs)\n",
      "  File \"<ipython-input-3-6c970680c913>\", line 51, in post\n",
      "    \n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\scoping.py\", line 153, in do\n",
      "    return getattr(self.registry(), name)(*args, **kwargs)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 943, in commit\n",
      "    self.transaction.commit()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 467, in commit\n",
      "    self._prepare_impl()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 447, in _prepare_impl\n",
      "    self.session.flush()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2254, in flush\n",
      "    self._flush(objects)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2380, in _flush\n",
      "    transaction.rollback(_capture_exception=True)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 66, in __exit__\n",
      "    compat.reraise(exc_type, exc_value, exc_tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 187, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2344, in _flush\n",
      "    flush_context.execute()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py\", line 391, in execute\n",
      "    rec.execute(self)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py\", line 556, in execute\n",
      "    uow\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py\", line 181, in save_obj\n",
      "    mapper, table, insert)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py\", line 830, in _emit_insert_statements\n",
      "    execute(statement, multiparams)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 948, in execute\n",
      "    return meth(self, multiparams, params)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\sql\\elements.py\", line 269, in _execute_on_connection\n",
      "    return connection._execute_clauseelement(self, multiparams, params)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1060, in _execute_clauseelement\n",
      "    compiled_sql, distilled_params\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1200, in _execute_context\n",
      "    context)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1413, in _handle_dbapi_exception\n",
      "    exc_info\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 203, in raise_from_cause\n",
      "    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 186, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1193, in _execute_context\n",
      "    context)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 507, in do_execute\n",
      "    cursor.execute(statement, parameters)\n",
      "sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: puppy.name [SQL: 'INSERT INTO puppy (name) VALUES (?)'] [parameters: ('Avik',)] (Background on this error at: http://sqlalche.me/e/gkpj)\n",
      "127.0.0.1 - - [22/Nov/2019 09:30:46] \"GET /puppy/Avik HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [22/Nov/2019 09:30:52] \"POST /puppy/Avik HTTP/1.1\" 500 -\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 2309, in __call__\n",
      "    return self.wsgi_app(environ, start_response)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 2295, in wsgi_app\n",
      "    response = self.handle_exception(e)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask_restful\\__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1741, in handle_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\_compat.py\", line 34, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 2292, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1815, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask_restful\\__init__.py\", line 269, in error_router\n",
      "    return original_handler(e)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1718, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\_compat.py\", line 34, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1813, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\app.py\", line 1799, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask_restful\\__init__.py\", line 458, in wrapper\n",
      "    resp = resource(*args, **kwargs)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask\\views.py\", line 88, in view\n",
      "    return self.dispatch_request(*args, **kwargs)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\flask_restful\\__init__.py\", line 573, in dispatch_request\n",
      "    resp = meth(*args, **kwargs)\n",
      "  File \"<ipython-input-3-6c970680c913>\", line 51, in post\n",
      "    \n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\scoping.py\", line 153, in do\n",
      "    return getattr(self.registry(), name)(*args, **kwargs)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 943, in commit\n",
      "    self.transaction.commit()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 467, in commit\n",
      "    self._prepare_impl()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 447, in _prepare_impl\n",
      "    self.session.flush()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2254, in flush\n",
      "    self._flush(objects)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2380, in _flush\n",
      "    transaction.rollback(_capture_exception=True)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 66, in __exit__\n",
      "    compat.reraise(exc_type, exc_value, exc_tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 187, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2344, in _flush\n",
      "    flush_context.execute()\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py\", line 391, in execute\n",
      "    rec.execute(self)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\unitofwork.py\", line 556, in execute\n",
      "    uow\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py\", line 181, in save_obj\n",
      "    mapper, table, insert)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\orm\\persistence.py\", line 830, in _emit_insert_statements\n",
      "    execute(statement, multiparams)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 948, in execute\n",
      "    return meth(self, multiparams, params)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\sql\\elements.py\", line 269, in _execute_on_connection\n",
      "    return connection._execute_clauseelement(self, multiparams, params)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1060, in _execute_clauseelement\n",
      "    compiled_sql, distilled_params\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1200, in _execute_context\n",
      "    context)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1413, in _handle_dbapi_exception\n",
      "    exc_info\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 203, in raise_from_cause\n",
      "    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 186, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1193, in _execute_context\n",
      "    context)\n",
      "  File \"C:\\Users\\ritis\\Anaconda3\\envs\\mynewflaskenv\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 507, in do_execute\n",
      "    cursor.execute(statement, parameters)\n",
      "sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: puppy.name [SQL: 'INSERT INTO puppy (name) VALUES (?)'] [parameters: ('Avik',)] (Background on this error at: http://sqlalche.me/e/gkpj)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [22/Nov/2019 09:30:59] \"POST /puppy/Antik HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [22/Nov/2019 09:31:03] \"GET /puppy/Antik HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [22/Nov/2019 09:31:08] \"DELETE /puppy/Antik HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [22/Nov/2019 09:31:18] \"DELETE /puppies HTTP/1.1\" 405 -\n",
      "127.0.0.1 - - [22/Nov/2019 09:32:47] \"DELETE /puppies HTTP/1.1\" 405 -\n"
     ]
    }
   ],
   "source": [
    "if __name__ == '__main__':\n",
    "    app.run(debug=True, use_reloader = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
